"""add verification_status to runs

Revision ID: 5631581e1505
Revises: 366054fe46bc
Create Date: 2026-06-17 10:11:36.736943
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5631581e1505'
down_revision: str | None = '366054fe46bc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.Enum('VERIFIED', 'LIKELY_MATCH', 'NEEDS_REVIEW', 'INSUFFICIENT_EVIDENCE', 'INACTIVE_NOT_ELIGIBLE', 'RISK_FLAG', name='verificationstatus', native_enum=False, length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_runs', schema=None) as batch_op:
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
