"""init core schema

Revision ID: 366054fe46bc
Revises: 
Create Date: 2026-06-17 09:57:13.318023
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '366054fe46bc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_legal_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('home_state', sa.String(length=2), nullable=True),
    sa.Column('status_normalized', sa.Enum('ACTIVE', 'INACTIVE', 'DISSOLVED', 'DELINQUENT', 'UNKNOWN', name='registrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('entity_age_days', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=550), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_companies_dedupe_key'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('source_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('states', sa.JSON(), nullable=False),
    sa.Column('cost_per_lookup', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_registry')),
    sa.UniqueConstraint('name', name=op.f('uq_source_registry_name'))
    )
    op.create_table('business_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('state_entity_id', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('formation_date', sa.Date(), nullable=True),
    sa.Column('status_raw', sa.String(length=200), nullable=True),
    sa.Column('status_normalized', sa.Enum('ACTIVE', 'INACTIVE', 'DISSOLVED', 'DELINQUENT', 'UNKNOWN', name='registrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_business_registrations_company_id_companies')),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_business_registrations_source_id_source_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_registrations')),
    sa.UniqueConstraint('state', 'state_entity_id', name='state_entity')
    )
    op.create_table('company_identifiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('id_type', sa.Enum('STATE_REG', 'UEI', 'EIN_HASH', 'DUNS', 'DOMAIN', name='identifiertype', native_enum=False, length=20), nullable=False),
    sa.Column('id_value', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_identifiers_company_id_companies')),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_company_identifiers_source_id_source_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_identifiers')),
    sa.UniqueConstraint('id_type', 'id_value', name='id_type_value')
    )
    op.create_table('company_officers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('screened_ofac', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_company_officers_company_id_companies')),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_company_officers_source_id_source_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_officers'))
    )
    op.create_table('salesforce_sync_status',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('sf_object', sa.String(length=50), nullable=False),
    sa.Column('sf_record_id', sa.String(length=50), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', name='syncstatus', native_enum=False, length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_salesforce_sync_status_company_id_companies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salesforce_sync_status')),
    sa.UniqueConstraint('sf_object', 'sf_record_id', name='sf_object_record')
    )
    op.create_table('source_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('secret_ref', sa.String(length=500), nullable=False),
    sa.Column('env', sa.String(length=20), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_source_credentials_source_id_source_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_credentials'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('sso_sub', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('sso_sub', name=op.f('uq_users_sso_sub'))
    )
    op.create_table('generated_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('storage_uri', sa.String(length=1000), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_generated_reports_company_id_companies')),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_generated_reports_generated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_reports'))
    )
    op.create_table('registered_agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(length=300), nullable=True),
    sa.Column('agent_address', sa.String(length=500), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['business_registrations.id'], name=op.f('fk_registered_agents_registration_id_business_registrations')),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_registered_agents_source_id_source_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registered_agents'))
    )
    op.create_table('verification_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SOURCE_UNAVAILABLE', name='runstatus', native_enum=False, length=30), nullable=False),
    sa.Column('score_version', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_verification_runs_company_id_companies')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_verification_runs_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_runs'))
    )
    op.create_table('confidence_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_run_id', sa.Uuid(), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_run_id'], ['verification_runs.id'], name=op.f('fk_confidence_scores_verification_run_id_verification_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confidence_scores'))
    )
    op.create_table('error_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['verification_runs.id'], name=op.f('fk_error_logs_run_id_verification_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_error_logs_source_id_source_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_logs'))
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_run_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('SCREENSHOT', 'RAW_JSON', 'PDF', name='evidencetype', native_enum=False, length=20), nullable=False),
    sa.Column('storage_uri', sa.String(length=1000), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_run_id'], ['verification_runs.id'], name=op.f('fk_evidence_items_verification_run_id_verification_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items'))
    )
    op.create_table('raw_source_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response_blob', sa.JSON(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('cost_credits', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_raw_source_events_source_id_source_registry')),
    sa.ForeignKeyConstraint(['verification_run_id'], ['verification_runs.id'], name=op.f('fk_raw_source_events_verification_run_id_verification_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_source_events'))
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('verification_run_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'NEEDS_MORE_INFO', name='reviewdecision', native_enum=False, length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('candidate_chosen', sa.String(length=255), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_decisions_reviewer_id_users')),
    sa.ForeignKeyConstraint(['verification_run_id'], ['verification_runs.id'], name=op.f('fk_review_decisions_verification_run_id_verification_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions'))
    )
    # ### end Alembic commands ###

    # Postgres-only: trigram index for fast fuzzy name search (plan §7.1).
    # Requires the pg_trgm extension. Skipped on SQLite (test suite).
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute(
            "CREATE INDEX ix_companies_normalized_name_trgm "
            "ON companies USING gin (normalized_name gin_trgm_ops)"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP INDEX IF EXISTS ix_companies_normalized_name_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_decisions')
    op.drop_table('raw_source_events')
    op.drop_table('evidence_items')
    op.drop_table('error_logs')
    op.drop_table('confidence_scores')
    op.drop_table('verification_runs')
    op.drop_table('registered_agents')
    op.drop_table('generated_reports')
    op.drop_table('users')
    op.drop_table('source_credentials')
    op.drop_table('salesforce_sync_status')
    op.drop_table('company_officers')
    op.drop_table('company_identifiers')
    op.drop_table('business_registrations')
    op.drop_table('source_registry')
    op.drop_table('roles')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_normalized_name'))

    op.drop_table('companies')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
