"""add ct and or staging tables

Revision ID: dda7437671e4
Revises: 48fe7ca4342a
Create Date: 2026-06-18 14:02:42.137775
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dda7437671e4'
down_revision: str | None = '48fe7ca4342a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ct_business_entities',
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('status_raw', sa.String(length=200), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('formation_date', sa.Date(), nullable=True),
    sa.Column('principal_address', sa.Text(), nullable=True),
    sa.Column('agent_name', sa.String(length=300), nullable=True),
    sa.Column('agent_address', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_ct_business_entities'))
    )
    with op.batch_alter_table('ct_business_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ct_business_entities_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('or_business_entities',
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('status_raw', sa.String(length=200), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('formation_date', sa.Date(), nullable=True),
    sa.Column('principal_address', sa.Text(), nullable=True),
    sa.Column('agent_name', sa.String(length=300), nullable=True),
    sa.Column('agent_address', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_or_business_entities'))
    )
    with op.batch_alter_table('or_business_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_or_business_entities_normalized_name'), ['normalized_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('or_business_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_or_business_entities_normalized_name'))

    op.drop_table('or_business_entities')
    with op.batch_alter_table('ct_business_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ct_business_entities_normalized_name'))

    op.drop_table('ct_business_entities')
    # ### end Alembic commands ###
