"""add_principal_address_to_business_registrations

Revision ID: e99621b7f97c
Revises: dda7437671e4
Create Date: 2026-06-18 14:32:33.788794
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e99621b7f97c'
down_revision: str | None = 'dda7437671e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_address', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_registrations', schema=None) as batch_op:
        batch_op.drop_column('principal_address')

    # ### end Alembic commands ###
